<?php
// database/seeders/CountrySeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    public function run()
    {
        // First, let's add country codes to the existing data from your SQL file
        $countries = [
            ['code' => 'AF', 'name' => 'Afghanistan', 'capital' => 'Kabul', 'region' => 'Asia'],
            ['code' => 'AL', 'name' => 'Albania', 'capital' => 'Tirana', 'region' => 'Europe'],
            ['code' => 'DZ', 'name' => 'Algeria', 'capital' => 'Algiers', 'region' => 'Africa'],
            ['code' => 'AO', 'name' => 'Angola', 'capital' => 'Luanda', 'region' => 'Africa'],
            ['code' => 'AR', 'name' => 'Argentina', 'capital' => 'Buenos Aires', 'region' => 'Americas'],
            ['code' => 'AM', 'name' => 'Armenia', 'capital' => 'Yerevan', 'region' => 'Asia'],
            ['code' => 'AU', 'name' => 'Australia', 'capital' => 'Canberra', 'region' => 'Oceania'],
            ['code' => 'AT', 'name' => 'Austria', 'capital' => 'Vienna', 'region' => 'Europe'],
            ['code' => 'AZ', 'name' => 'Azerbaijan', 'capital' => 'Baku', 'region' => 'Asia'],
            ['code' => 'BH', 'name' => 'Bahrain', 'capital' => 'Manama', 'region' => 'Asia'],
            ['code' => 'BD', 'name' => 'Bangladesh', 'capital' => 'Dhaka', 'region' => 'Asia'],
            ['code' => 'BY', 'name' => 'Belarus', 'capital' => 'Minsk', 'region' => 'Europe'],
            ['code' => 'BE', 'name' => 'Belgium', 'capital' => 'Brussels', 'region' => 'Europe'],
            ['code' => 'BZ', 'name' => 'Belize', 'capital' => 'Belmopan', 'region' => 'Americas'],
            ['code' => 'BJ', 'name' => 'Benin', 'capital' => 'Porto-Novo', 'region' => 'Africa'],
            ['code' => 'BT', 'name' => 'Bhutan', 'capital' => 'Thimphu', 'region' => 'Asia'],
            ['code' => 'BO', 'name' => 'Bolivia', 'capital' => 'Sucre', 'region' => 'Americas'],
            ['code' => 'BA', 'name' => 'Bosnia and Herzegovina', 'capital' => 'Sarajevo', 'region' => 'Europe'],
            ['code' => 'BW', 'name' => 'Botswana', 'capital' => 'Gaborone', 'region' => 'Africa'],
            ['code' => 'BR', 'name' => 'Brazil', 'capital' => 'Brasília', 'region' => 'Americas'],
            ['code' => 'BG', 'name' => 'Bulgaria', 'capital' => 'Sofia', 'region' => 'Europe'],
            ['code' => 'BF', 'name' => 'Burkina Faso', 'capital' => 'Ouagadougou', 'region' => 'Africa'],
            ['code' => 'BI', 'name' => 'Burundi', 'capital' => 'Gitega', 'region' => 'Africa'],
            ['code' => 'KH', 'name' => 'Cambodia', 'capital' => 'Phnom Penh', 'region' => 'Asia'],
            ['code' => 'CM', 'name' => 'Cameroon', 'capital' => 'Yaoundé', 'region' => 'Africa'],
            ['code' => 'CA', 'name' => 'Canada', 'capital' => 'Ottawa', 'region' => 'Americas'],
            ['code' => 'CV', 'name' => 'Cabo Verde', 'capital' => 'Praia', 'region' => 'Africa'],
            ['code' => 'CF', 'name' => 'Central African Republic', 'capital' => 'Bangui', 'region' => 'Africa'],
            ['code' => 'TD', 'name' => 'Chad', 'capital' => 'N\'Djamena', 'region' => 'Africa'],
            ['code' => 'CL', 'name' => 'Chile', 'capital' => 'Santiago', 'region' => 'Americas'],
            ['code' => 'CN', 'name' => 'China', 'capital' => 'Beijing', 'region' => 'Asia'],
            ['code' => 'CO', 'name' => 'Colombia', 'capital' => 'Bogotá', 'region' => 'Americas'],
            ['code' => 'KM', 'name' => 'Comoros', 'capital' => 'Moroni', 'region' => 'Africa'],
            ['code' => 'CG', 'name' => 'Congo', 'capital' => 'Brazzaville', 'region' => 'Africa'],
            ['code' => 'CR', 'name' => 'Costa Rica', 'capital' => 'San José', 'region' => 'Americas'],
            ['code' => 'HR', 'name' => 'Croatia', 'capital' => 'Zagreb', 'region' => 'Europe'],
            ['code' => 'CU', 'name' => 'Cuba', 'capital' => 'Havana', 'region' => 'Americas'],
            ['code' => 'CY', 'name' => 'Cyprus', 'capital' => 'Nicosia', 'region' => 'Europe'],
            ['code' => 'CZ', 'name' => 'Czech Republic', 'capital' => 'Prague', 'region' => 'Europe'],
            ['code' => 'DK', 'name' => 'Denmark', 'capital' => 'Copenhagen', 'region' => 'Europe'],
            ['code' => 'DJ', 'name' => 'Djibouti', 'capital' => 'Djibouti', 'region' => 'Africa'],
            ['code' => 'DO', 'name' => 'Dominican Republic', 'capital' => 'Santo Domingo', 'region' => 'Americas'],
            ['code' => 'EC', 'name' => 'Ecuador', 'capital' => 'Quito', 'region' => 'Americas'],
            ['code' => 'EG', 'name' => 'Egypt', 'capital' => 'Cairo', 'region' => 'Africa'],
            ['code' => 'SV', 'name' => 'El Salvador', 'capital' => 'San Salvador', 'region' => 'Americas'],
            ['code' => 'GQ', 'name' => 'Equatorial Guinea', 'capital' => 'Malabo', 'region' => 'Africa'],
            ['code' => 'EE', 'name' => 'Estonia', 'capital' => 'Tallinn', 'region' => 'Europe'],
            ['code' => 'ET', 'name' => 'Ethiopia', 'capital' => 'Addis Ababa', 'region' => 'Africa'],
            ['code' => 'FJ', 'name' => 'Fiji', 'capital' => 'Suva', 'region' => 'Oceania'],
            ['code' => 'FI', 'name' => 'Finland', 'capital' => 'Helsinki', 'region' => 'Europe'],
            ['code' => 'FR', 'name' => 'France', 'capital' => 'Paris', 'region' => 'Europe'],
            ['code' => 'GA', 'name' => 'Gabon', 'capital' => 'Libreville', 'region' => 'Africa'],
            ['code' => 'GE', 'name' => 'Georgia', 'capital' => 'Tbilisi', 'region' => 'Asia'],
            ['code' => 'DE', 'name' => 'Germany', 'capital' => 'Berlin', 'region' => 'Europe'],
            ['code' => 'GH', 'name' => 'Ghana', 'capital' => 'Accra', 'region' => 'Africa'],
            ['code' => 'GR', 'name' => 'Greece', 'capital' => 'Athens', 'region' => 'Europe'],
            ['code' => 'GT', 'name' => 'Guatemala', 'capital' => 'Guatemala City', 'region' => 'Americas'],
            ['code' => 'GN', 'name' => 'Guinea', 'capital' => 'Conakry', 'region' => 'Africa'],
            ['code' => 'GW', 'name' => 'Guinea-Bissau', 'capital' => 'Bissau', 'region' => 'Africa'],
            ['code' => 'GY', 'name' => 'Guyana', 'capital' => 'Georgetown', 'region' => 'Americas'],
            ['code' => 'HT', 'name' => 'Haiti', 'capital' => 'Port-au-Prince', 'region' => 'Americas'],
            ['code' => 'VA', 'name' => 'Vatican City', 'capital' => 'Vatican City', 'region' => 'Europe'],
            ['code' => 'HN', 'name' => 'Honduras', 'capital' => 'Tegucigalpa', 'region' => 'Americas'],
            ['code' => 'HK', 'name' => 'Hong Kong', 'capital' => 'City of Victoria', 'region' => 'Asia'],
            ['code' => 'HU', 'name' => 'Hungary', 'capital' => 'Budapest', 'region' => 'Europe'],
            ['code' => 'IS', 'name' => 'Iceland', 'capital' => 'Reykjavík', 'region' => 'Europe'],
            ['code' => 'IN', 'name' => 'India', 'capital' => 'New Delhi', 'region' => 'Asia'],
            ['code' => 'ID', 'name' => 'Indonesia', 'capital' => 'Jakarta', 'region' => 'Asia'],
            ['code' => 'CI', 'name' => 'Côte d\'Ivoire', 'capital' => 'Yamoussoukro', 'region' => 'Africa'],
            ['code' => 'IR', 'name' => 'Iran', 'capital' => 'Tehran', 'region' => 'Asia'],
            ['code' => 'IQ', 'name' => 'Iraq', 'capital' => 'Baghdad', 'region' => 'Asia'],
            ['code' => 'IE', 'name' => 'Ireland', 'capital' => 'Dublin', 'region' => 'Europe'],
            ['code' => 'IL', 'name' => 'Israel', 'capital' => 'Jerusalem', 'region' => 'Asia'],
            ['code' => 'IT', 'name' => 'Italy', 'capital' => 'Rome', 'region' => 'Europe'],
            ['code' => 'JM', 'name' => 'Jamaica', 'capital' => 'Kingston', 'region' => 'Americas'],
            ['code' => 'JP', 'name' => 'Japan', 'capital' => 'Tokyo', 'region' => 'Asia'],
            ['code' => 'JO', 'name' => 'Jordan', 'capital' => 'Amman', 'region' => 'Asia'],
            ['code' => 'KZ', 'name' => 'Kazakhstan', 'capital' => 'Nur-Sultan', 'region' => 'Asia'],
            ['code' => 'KE', 'name' => 'Kenya', 'capital' => 'Nairobi', 'region' => 'Africa'],
            ['code' => 'KW', 'name' => 'Kuwait', 'capital' => 'Kuwait City', 'region' => 'Asia'],
            ['code' => 'KG', 'name' => 'Kyrgyzstan', 'capital' => 'Bishkek', 'region' => 'Asia'],
            ['code' => 'LA', 'name' => 'Laos', 'capital' => 'Vientiane', 'region' => 'Asia'],
            ['code' => 'LV', 'name' => 'Latvia', 'capital' => 'Riga', 'region' => 'Europe'],
            ['code' => 'LB', 'name' => 'Lebanon', 'capital' => 'Beirut', 'region' => 'Asia'],
            ['code' => 'LS', 'name' => 'Lesotho', 'capital' => 'Maseru', 'region' => 'Africa'],
            ['code' => 'LR', 'name' => 'Liberia', 'capital' => 'Monrovia', 'region' => 'Africa'],
            ['code' => 'LY', 'name' => 'Libya', 'capital' => 'Tripoli', 'region' => 'Africa'],
            ['code' => 'LT', 'name' => 'Lithuania', 'capital' => 'Vilnius', 'region' => 'Europe'],
            ['code' => 'LU', 'name' => 'Luxembourg', 'capital' => 'Luxembourg', 'region' => 'Europe'],
            ['code' => 'MK', 'name' => 'North Macedonia', 'capital' => 'Skopje', 'region' => 'Europe'],
            ['code' => 'MG', 'name' => 'Madagascar', 'capital' => 'Antananarivo', 'region' => 'Africa'],
            ['code' => 'MW', 'name' => 'Malawi', 'capital' => 'Lilongwe', 'region' => 'Africa'],
            ['code' => 'MY', 'name' => 'Malaysia', 'capital' => 'Kuala Lumpur', 'region' => 'Asia'],
            ['code' => 'MV', 'name' => 'Maldives', 'capital' => 'Malé', 'region' => 'Asia'],
            ['code' => 'ML', 'name' => 'Mali', 'capital' => 'Bamako', 'region' => 'Africa'],
            ['code' => 'MT', 'name' => 'Malta', 'capital' => 'Valletta', 'region' => 'Europe'],
            ['code' => 'MR', 'name' => 'Mauritania', 'capital' => 'Nouakchott', 'region' => 'Africa'],
            ['code' => 'MU', 'name' => 'Mauritius', 'capital' => 'Port Louis', 'region' => 'Africa'],
            ['code' => 'MX', 'name' => 'Mexico', 'capital' => 'Mexico City', 'region' => 'Americas'],
            ['code' => 'MD', 'name' => 'Moldova', 'capital' => 'Chișinău', 'region' => 'Europe'],
            ['code' => 'MN', 'name' => 'Mongolia', 'capital' => 'Ulan Bator', 'region' => 'Asia'],
            ['code' => 'ME', 'name' => 'Montenegro', 'capital' => 'Podgorica', 'region' => 'Europe'],
            ['code' => 'MA', 'name' => 'Morocco', 'capital' => 'Rabat', 'region' => 'Africa'],
            ['code' => 'MZ', 'name' => 'Mozambique', 'capital' => 'Maputo', 'region' => 'Africa'],
            ['code' => 'MM', 'name' => 'Myanmar', 'capital' => 'Naypyidaw', 'region' => 'Asia'],
            ['code' => 'NA', 'name' => 'Namibia', 'capital' => 'Windhoek', 'region' => 'Africa'],
            ['code' => 'NP', 'name' => 'Nepal', 'capital' => 'Kathmandu', 'region' => 'Asia'],
            ['code' => 'NL', 'name' => 'Netherlands', 'capital' => 'Amsterdam', 'region' => 'Europe'],
            ['code' => 'NZ', 'name' => 'New Zealand', 'capital' => 'Wellington', 'region' => 'Oceania'],
            ['code' => 'NI', 'name' => 'Nicaragua', 'capital' => 'Managua', 'region' => 'Americas'],
            ['code' => 'NE', 'name' => 'Niger', 'capital' => 'Niamey', 'region' => 'Africa'],
            ['code' => 'NG', 'name' => 'Nigeria', 'capital' => 'Abuja', 'region' => 'Africa'],
            ['code' => 'KP', 'name' => 'North Korea', 'capital' => 'Pyongyang', 'region' => 'Asia'],
            ['code' => 'NO', 'name' => 'Norway', 'capital' => 'Oslo', 'region' => 'Europe'],
            ['code' => 'OM', 'name' => 'Oman', 'capital' => 'Muscat', 'region' => 'Asia'],
            ['code' => 'PK', 'name' => 'Pakistan', 'capital' => 'Islamabad', 'region' => 'Asia'],
            ['code' => 'PA', 'name' => 'Panama', 'capital' => 'Panama City', 'region' => 'Americas'],
            ['code' => 'PG', 'name' => 'Papua New Guinea', 'capital' => 'Port Moresby', 'region' => 'Oceania'],
            ['code' => 'PY', 'name' => 'Paraguay', 'capital' => 'Asunción', 'region' => 'Americas'],
            ['code' => 'PE', 'name' => 'Peru', 'capital' => 'Lima', 'region' => 'Americas'],
            ['code' => 'PH', 'name' => 'Philippines', 'capital' => 'Manila', 'region' => 'Asia'],
            ['code' => 'PL', 'name' => 'Poland', 'capital' => 'Warsaw', 'region' => 'Europe'],
            ['code' => 'PT', 'name' => 'Portugal', 'capital' => 'Lisbon', 'region' => 'Europe'],
            ['code' => 'QA', 'name' => 'Qatar', 'capital' => 'Doha', 'region' => 'Asia'],
            ['code' => 'RO', 'name' => 'Romania', 'capital' => 'Bucharest', 'region' => 'Europe'],
            ['code' => 'RU', 'name' => 'Russia', 'capital' => 'Moscow', 'region' => 'Europe'],
            ['code' => 'RW', 'name' => 'Rwanda', 'capital' => 'Kigali', 'region' => 'Africa'],
            ['code' => 'LC', 'name' => 'Saint Lucia', 'capital' => 'Castries', 'region' => 'Americas'],
            ['code' => 'ST', 'name' => 'Sao Tome and Principe', 'capital' => 'São Tomé', 'region' => 'Africa'],
            ['code' => 'SA', 'name' => 'Saudi Arabia', 'capital' => 'Riyadh', 'region' => 'Asia'],
            ['code' => 'SN', 'name' => 'Senegal', 'capital' => 'Dakar', 'region' => 'Africa'],
            ['code' => 'RS', 'name' => 'Serbia', 'capital' => 'Belgrade', 'region' => 'Europe'],
            ['code' => 'SC', 'name' => 'Seychelles', 'capital' => 'Victoria', 'region' => 'Africa'],
            ['code' => 'SL', 'name' => 'Sierra Leone', 'capital' => 'Freetown', 'region' => 'Africa'],
            ['code' => 'SG', 'name' => 'Singapore', 'capital' => 'Singapore', 'region' => 'Asia'],
            ['code' => 'SK', 'name' => 'Slovakia', 'capital' => 'Bratislava', 'region' => 'Europe'],
            ['code' => 'SI', 'name' => 'Slovenia', 'capital' => 'Ljubljana', 'region' => 'Europe'],
            ['code' => 'SO', 'name' => 'Somalia', 'capital' => 'Mogadishu', 'region' => 'Africa'],
            ['code' => 'ZA', 'name' => 'South Africa', 'capital' => 'Pretoria', 'region' => 'Africa'],
            ['code' => 'KR', 'name' => 'South Korea', 'capital' => 'Seoul', 'region' => 'Asia'],
            ['code' => 'SS', 'name' => 'South Sudan', 'capital' => 'Juba', 'region' => 'Africa'],
            ['code' => 'ES', 'name' => 'Spain', 'capital' => 'Madrid', 'region' => 'Europe'],
            ['code' => 'LK', 'name' => 'Sri Lanka', 'capital' => 'Sri Jayawardenepura Kotte', 'region' => 'Asia'],
            ['code' => 'SD', 'name' => 'Sudan', 'capital' => 'Khartoum', 'region' => 'Africa'],
            ['code' => 'SR', 'name' => 'Suriname', 'capital' => 'Paramaribo', 'region' => 'Americas'],
            ['code' => 'SZ', 'name' => 'Eswatini', 'capital' => 'Mbabane', 'region' => 'Africa'],
            ['code' => 'SE', 'name' => 'Sweden', 'capital' => 'Stockholm', 'region' => 'Europe'],
            ['code' => 'CH', 'name' => 'Switzerland', 'capital' => 'Bern', 'region' => 'Europe'],
            ['code' => 'SY', 'name' => 'Syria', 'capital' => 'Damascus', 'region' => 'Asia'],
            ['code' => 'TW', 'name' => 'Taiwan', 'capital' => 'Taipei', 'region' => 'Asia'],
            ['code' => 'TJ', 'name' => 'Tajikistan', 'capital' => 'Dushanbe', 'region' => 'Asia'],
            ['code' => 'TZ', 'name' => 'Tanzania', 'capital' => 'Dodoma', 'region' => 'Africa'],
            ['code' => 'TH', 'name' => 'Thailand', 'capital' => 'Bangkok', 'region' => 'Asia'],
            ['code' => 'TL', 'name' => 'Timor-Leste', 'capital' => 'Dili', 'region' => 'Asia'],
            ['code' => 'TG', 'name' => 'Togo', 'capital' => 'Lomé', 'region' => 'Africa'],
            ['code' => 'TT', 'name' => 'Trinidad and Tobago', 'capital' => 'Port of Spain', 'region' => 'Americas'],
            ['code' => 'TN', 'name' => 'Tunisia', 'capital' => 'Tunis', 'region' => 'Africa'],
            ['code' => 'TR', 'name' => 'Turkey', 'capital' => 'Ankara', 'region' => 'Asia'],
            ['code' => 'TM', 'name' => 'Turkmenistan', 'capital' => 'Ashgabat', 'region' => 'Asia'],
            ['code' => 'UG', 'name' => 'Uganda', 'capital' => 'Kampala', 'region' => 'Africa'],
            ['code' => 'UA', 'name' => 'Ukraine', 'capital' => 'Kyiv', 'region' => 'Europe'],
            ['code' => 'AE', 'name' => 'United Arab Emirates', 'capital' => 'Abu Dhabi', 'region' => 'Asia'],
            ['code' => 'GB', 'name' => 'United Kingdom', 'capital' => 'London', 'region' => 'Europe'],
            ['code' => 'US', 'name' => 'United States', 'capital' => 'Washington, D.C.', 'region' => 'Americas'],
            ['code' => 'UY', 'name' => 'Uruguay', 'capital' => 'Montevideo', 'region' => 'Americas'],
            ['code' => 'UZ', 'name' => 'Uzbekistan', 'capital' => 'Tashkent', 'region' => 'Asia'],
            ['code' => 'VE', 'name' => 'Venezuela', 'capital' => 'Caracas', 'region' => 'Americas'],
            ['code' => 'VN', 'name' => 'Vietnam', 'capital' => 'Hanoi', 'region' => 'Asia'],
            ['code' => 'YE', 'name' => 'Yemen', 'capital' => 'Sana\'a', 'region' => 'Asia'],
            ['code' => 'ZM', 'name' => 'Zambia', 'capital' => 'Lusaka', 'region' => 'Africa'],
            ['code' => 'ZW', 'name' => 'Zimbabwe', 'capital' => 'Harare', 'region' => 'Africa'],
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}