INSERT INTO countries (alpha2Code, region, name, capital) VALUES
  ('AF', 'Asia','Afghanistan','Kabul'),
  ('AL', 'Europe','Albania','Tirana'),
  ('DZ', 'Africa','Algeria','Algiers'),
  ('AO', 'Africa','Angola','Luanda'),
  ('AR', 'Americas','Argentina','Buenos Aires'),
  ('AM', 'Asia','Armenia','Yerevan'),
  ('AU', 'Oceania','Australia','Canberra'),
  ('AT', 'Europe','Austria','Vienna'),
  ('AZ', 'Asia','Azerbaijan','Baku'),
  ('BH', 'Asia','Bahrain','Manama'),
  ('BD', 'Asia','Bangladesh','Dhaka'),
  ('BY', 'Europe','Belarus','Minsk'),
  ('BE', 'Europe','Belgium','Brussels'),
  ('BZ', 'Americas','Belize','Belmopan'),
  ('BJ', 'Africa','Benin','Porto-Novo'),
  ('BT', 'Asia','Bhutan','Thimphu'),
  ('BO', 'Americas','Bolivia','Sucre'),
  ('BA', 'Europe','Bosnia and Herzegovina','Sarajevo'),
  ('BW', 'Africa','Botswana','Gaborone'),
  ('BR', 'Americas','Brazil','Brasília'),
  ('BG', 'Europe','Bulgaria','Sofia'),
  ('BF', 'Africa','Burkina Faso','Ouagadougou'),
  ('BI', 'Africa','Burundi','Gitega'),
  ('KH', 'Asia','Cambodia','Phnom Penh'),
  ('CM', 'Africa','Cameroon','Yaoundé'),
  ('CA', 'Americas','Canada','Ottawa'),
  ('CV', 'Africa','Cabo Verde','Praia'),
  ('CF', 'Africa','Central African Republic','Bangui'),
  ('TD', 'Africa','Chad','N''Djamena'),
  ('CL', 'Americas','Chile','Santiago'),
  ('CN', 'Asia','China','Beijing'),
  ('CO', 'Americas','Colombia','Bogotá'),
  ('KM', 'Africa','Comoros','Moroni'),
  ('CG', 'Africa','Congo','Brazzaville'),
  ('CR', 'Americas','Costa Rica','San José'),
  ('HR', 'Europe','Croatia','Zagreb'),
  ('CU', 'Americas','Cuba','Havana'),
  ('CY', 'Europe','Cyprus','Nicosia'),
  ('CZ', 'Europe','Czech Republic','Prague'),
  ('DK', 'Europe','Denmark','Copenhagen'),
  ('DJ', 'Africa','Djibouti','Djibouti'),
  ('DO', 'Americas','Dominican Republic','Santo Domingo'),
  ('EC', 'Americas','Ecuador','Quito'),
  ('EG', 'Africa','Egypt','Cairo'),
  ('SV', 'Americas','El Salvador','San Salvador'),
  ('GQ', 'Africa','Equatorial Guinea','Malabo'),
  ('EE', 'Europe','Estonia','Tallinn'),
  ('ET', 'Africa','Ethiopia','Addis Ababa'),
  ('FJ', 'Oceania','Fiji','Suva'),
  ('FI', 'Europe','Finland','Helsinki'),
  ('FR', 'Europe','France','Paris'),
  ('GA', 'Africa','Gabon','Libreville'),
  ('GE', 'Asia','Georgia','Tbilisi'),
  ('DE', 'Europe','Germany','Berlin'),
  ('GH', 'Africa','Ghana','Accra'),
  ('GR', 'Europe','Greece','Athens'),
  ('GT', 'Americas','Guatemala','Guatemala City'),
  ('GN', 'Africa','Guinea','Conakry'),
  ('GW', 'Africa','Guinea-Bissau','Bissau'),
  ('GY', 'Americas','Guyana','Georgetown'),
  ('HT', 'Americas','Haiti','Port-au-Prince'),
  ('VA', 'Europe','Vatican City','Vatican City'),
  ('HN', 'Americas','Honduras','Tegucigalpa'),
  ('HK', 'Asia','Hong Kong','City of Victoria'),
  ('HU', 'Europe','Hungary','Budapest'),
  ('IS', 'Europe','Iceland','Reykjavík'),
  ('IN', 'Asia','India','New Delhi'),
  ('ID', 'Asia','Indonesia','Jakarta'),
  ('CI', 'Africa','Côte d''Ivoire','Yamoussoukro'),
  ('IR', 'Asia','Iran','Tehran'),
  ('IQ', 'Asia','Iraq','Baghdad'),
  ('IE', 'Europe','Ireland','Dublin'),
  ('IL', 'Asia','Israel','Jerusalem'),
  ('IT', 'Europe','Italy','Rome'),
  ('JM', 'Americas','Jamaica','Kingston'),
  ('JP', 'Asia','Japan','Tokyo'),
  ('JO', 'Asia','Jordan','Amman'),
  ('KZ', 'Asia','Kazakhstan','Nur-Sultan'),
  ('KE', 'Africa','Kenya','Nairobi'),
  ('KW', 'Asia','Kuwait','Kuwait City'),
  ('KG', 'Asia','Kyrgyzstan','Bishkek'),
  ('LA', 'Asia','Lao People''s Democratic Republic','Vientiane'),
  ('LV', 'Europe','Latvia','Riga'),
  ('LB', 'Asia','Lebanon','Beirut'),
  ('LS', 'Africa','Lesotho','Maseru'),
  ('LR', 'Africa','Liberia','Monrovia'),
  ('LY', 'Africa','Libya','Tripoli'),
  ('LT', 'Europe','Lithuania','Vilnius'),
  ('LU', 'Europe','Luxembourg','Luxembourg'),
  ('MK', 'Europe','North Macedonia','Skopje'),
  ('MG', 'Africa','Madagascar','Antananarivo'),
  ('MW', 'Africa','Malawi','Lilongwe'),
  ('MY', 'Asia','Malaysia','Kuala Lumpur'),
  ('MV', 'Asia','Maldives','Malé'),
  ('ML', 'Africa','Mali','Bamako'),
  ('MT', 'Europe','Malta','Valletta'),
  ('MR', 'Africa','Mauritania','Nouakchott'),
  ('MU', 'Africa','Mauritius','Port Louis'),
  ('MX', 'Americas','Mexico','Mexico City'),
  ('MD', 'Europe','Moldova','Chișinău'),
  ('MN', 'Asia','Mongolia','Ulan Bator'),
  ('ME', 'Europe','Montenegro','Podgorica'),
  ('MA', 'Africa','Morocco','Rabat'),
  ('MZ', 'Africa','Mozambique','Maputo'),
  ('MM', 'Asia','Myanmar','Naypyidaw'),
  ('NA', 'Africa','Namibia','Windhoek'),
  ('NP', 'Asia','Nepal','Kathmandu'),
  ('NL', 'Europe','Netherlands','Amsterdam'),
  ('NZ', 'Oceania','New Zealand','Wellington'),
  ('NI', 'Americas','Nicaragua','Managua'),
  ('NE', 'Africa','Niger','Niamey'),
  ('NG', 'Africa','Nigeria','Abuja'),
  ('KP', 'Asia','North Korea','Pyongyang'),
  ('NO', 'Europe','Norway','Oslo'),
  ('OM', 'Asia','Oman','Muscat'),
  ('PK', 'Asia','Pakistan','Islamabad'),
  ('PA', 'Americas','Panama','Panama City'),
  ('PG', 'Oceania','Papua New Guinea','Port Moresby'),
  ('PY', 'Americas','Paraguay','Asunción'),
  ('PE', 'Americas','Peru','Lima'),
  ('PH', 'Asia','Philippines','Manila'),
  ('PL', 'Europe','Poland','Warsaw'),
  ('PT', 'Europe','Portugal','Lisbon'),
  ('QA', 'Asia','Qatar','Doha'),
  ('RO', 'Europe','Romania','Bucharest'),
  ('RU', 'Europe','Russian Federation','Moscow'),
  ('RW', 'Africa','Rwanda','Kigali'),
  ('LC', 'Americas','Saint Lucia','Castries'),
  ('ST', 'Africa','Sao Tome and Principe','São Tomé'),
  ('SA', 'Asia','Saudi Arabia','Riyadh'),
  ('SN', 'Africa','Senegal','Dakar'),
  ('RS', 'Europe','Serbia','Belgrade'),
  ('SC', 'Africa','Seychelles','Victoria'),
  ('SL', 'Africa','Sierra Leone','Freetown'),
  ('SG', 'Asia','Singapore','Singapore'),
  ('SK', 'Europe','Slovakia','Bratislava'),
  ('SI', 'Europe','Slovenia','Ljubljana'),
  ('SO', 'Africa','Somalia','Mogadishu'),
  ('ZA', 'Africa','South Africa','Pretoria'),
  ('KR', 'Asia','South Korea','Seoul'),
  ('SS', 'Africa','South Sudan','Juba'),
  ('ES', 'Europe','Spain','Madrid'),
  ('LK', 'Asia','Sri Lanka','Sri Jayawardenepura Kotte'),
  ('SD', 'Africa','Sudan','Khartoum'),
  ('SR', 'Americas','Suriname','Paramaribo'),
  ('SZ', 'Africa','Eswatini','Mbabane'),
  ('SE', 'Europe','Sweden','Stockholm'),
  ('CH', 'Europe','Switzerland','Bern'),
  ('SY', 'Asia','Syria','Damascus'),
  ('TW', 'Asia','Taiwan','Taipei'),
  ('TJ', 'Asia','Tajikistan','Dushanbe'),
  ('TZ', 'Africa','Tanzania','Dodoma'),
  ('TH', 'Asia','Thailand','Bangkok'),
  ('TL', 'Asia','Timor-Leste','Dili'),
  ('TG', 'Africa','Togo','Lomé'),
  ('TT', 'Americas','Trinidad and Tobago','Port of Spain'),
  ('TN', 'Africa','Tunisia','Tunis'),
  ('TR', 'Asia','Turkey','Ankara'),
  ('TM', 'Asia','Turkmenistan','Ashgabat'),
  ('UG', 'Africa','Uganda','Kampala'),
  ('UA', 'Europe','Ukraine','Kyiv'),
  ('AE', 'Asia','United Arab Emirates','Abu Dhabi'),
  ('US', 'Americas','United States of America','Washington, D.C.'),
  ('UY', 'Americas','Uruguay','Montevideo'),
  ('UZ', 'Asia','Uzbekistan','Tashkent'),
  ('VE', 'Americas','Venezuela','Caracas'),
  ('VN', 'Asia','Vietnam','Hanoi'),
  ('YE', 'Asia','Yemen','Sana''a'),
  ('ZM', 'Africa','Zambia','Lusaka'),
  ('ZW', 'Africa','Zimbabwe','Harare');