CREATE TABLE IF NOT EXISTS countries (
    alpha2Code VARCHAR(2) PRIMARY KEY,
    alpha3Code VARCHAR(3),
    altSpellings TEXT,
    area TEXT,
    borders TEXT,
    callingCodes TEXT,
    capital VARCHAR(255),
    currencies TEXT,
    demonym VARCHAR(255),
    flag VARCHAR(255),
    gini TEXT,
    languages TEXT,
    latlng TEXT,
    name VARCHAR(255) NOT NULL,
    nativeName VARCHAR(255),
    numericCode VARCHAR(10),
    population VARCHAR(50),
    region VARCHAR(100),
    regionalBlocs TEXT,
    subregion VARCHAR(100),
    timezones TEXT,
    topLevelDomain TEXT,
    translations TEXT,
    cioc VARCHAR(10)
);
